[build]
builder = "nixpacks"
buildCommand = "npx install -g pnpm && pnpm install"

[deploy]
startCommand = "npx pnpm start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
numReplicas = 1
healthcheckTimeout = 996
restartPolicyMaxRetries = 1


#https://docs.railway.app/deploy/config-as-code
