-- CreateTable
CREATE TABLE "Donation" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "count" INT4 NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "displayName" STRING NOT NULL,
    "email" STRING NOT NULL,
    "mobile" STRING,
    "message" STRING,
    "team" STRING,

    CONSTRAINT "Donation_pkey" PRIMARY KEY ("id")
);
